on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  "test":
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - uses: actions/checkout@v4

      - run: bun install

      - run: bun test
